trigger: none
pr: none

pool:
  vmImage: windows-2019

resources:
  containers:
  - container: test
    image: mcr.microsoft.com/windows/servercore:1809

stages:
- stage: dev
  displayName: dev
  jobs:
  - job: abcd
    displayName: abcd_Name
    
    steps:
      - powershell: |
          Write-Host "Set-TimeZone: W. Europe Standard Time"
          Set-TimeZone -Name "W. Europe Standard Time"
        displayName: Test123
    
