# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    echo "#### Check used ports:"
    netstat -ano
    echo "#### Check reserved ports:"
    netsh int ip show excludedportrange protocol=tcp
  displayName: 'Check ports'
    
- bash: |
    npm install -g azurite
    mkdir azurite
    azurite --silent --location azurite --debug azurite\debug.log &
  displayName: 'Install and Run Azurite'
    
- script: |
    echo "#### Check used ports:"
    netstat -ano
  displayName: 'Check ports'
    
