trigger: none

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    echo "#### 01"
    echo "#### 02"
    echo "#### npm globals"
    npm list -g
    echo "#### Test lerna version"
    lerna --version
    echo "#### npm globals"
    npm list -g
  displayName: 'Tests'
  
  
