trigger: none

pool:
  vmImage: 'windows-2019'

steps:
- script: |
    echo "#### 01"
    echo "#### 02"
    echo "#### npm globals"
    npm list -g
  displayName: 'Tests01'
  
- script: |
    echo "#### Node version"
    node --version
  displayName: 'Tests02'
  
- script: |
    echo "#### Npm version"
    npm --version
  displayName: 'Tests03'
  
- task: NodeTool@0
  inputs:
    versionSpec: '10.16.3'
  displayName: 'Install Node.js'
  
- script: |
    echo "#### Node version"
    node --version
  displayName: 'Test02b'
  
- script: |
    echo "#### Npm version"
    npm --version
  displayName: 'Test03b'
