trigger: none
pr: none

pool:
  vmImage: windows-2019

resources:
  containers:
  - container: Test_Container
    image: mcr.microsoft.com/windows/servercore:1809

stages:
- stage: Test_Build
  displayName: Test_Building
  jobs:
  - job: Test_Job
    displayName: Test_Job
    
    steps:
      - powershell: |
          Write-Host "Set-TimeZone: W. Europe Standard Time"
          Set-TimeZone -Name "W. Europe Standard Time"
        displayName: Set-TimeZone
    
