trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
     Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
     Start-Sleep -s 30
     dir "C:\Program Files\Azure Cosmos DB Emulator\"
     Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
     $startEmulatorCmd = "Start-CosmosDbEmulator -NoFirewall"
     Write-Host $startEmulatorCmd
     Invoke-Expression -Command $startEmulatorCmd
     Start-Sleep -s 30
     netstat -aob
     Invoke-WebRequest "https://localhost:8081/_explorer/index.html"
  displayName: 'Check ports'
