name: .NET 02 (with artifacts upload)

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
    - name: Upload Artifact 01
      uses: actions/upload-artifact@v2
      with:
        name: .net-app_01
        path: ${{env.DOTNET_ROOT}}/myapp
      
    - name: Upload Artifact 02
      uses: actions/upload-artifact@v2
      with:
        name: .net-app_02
        path: ${{env.DOTNET_ROOT}}/myapp
      
      
      
      
      
      
      
      
      

