name: .NET 01b

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: windows-19

    steps:
    - uses: actions/checkout@v3
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v2
#      with:
#        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore --runtime win-x86
    - name: Build
      run: dotnet build .\WebApplication01\WebApplication01.csproj --runtime win-x86 --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
