name: .NET 06 (just Win pwsh)

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v2
#      with:
#        dotnet-version: 6.0.x
        
    - name: PowerShell lines run
      shell: pwsh
      run: |
        echo "Bla Bla"
        echo "Bla Bla2"
        echo "Bla Bla3"
        $b1 = "Bla Bla4"
        echo $b1
        c:
        cd\
        echo "Bla Bla5"
        dir
        echo "Bla Bla6"
        Install-Script -Name Show-Tree -force
        echo "Bla Bla7"
        cd ProgramData
        echo "Bla Bla8"
        dir
        cd chocolatey
        dir
        cd..
        tree
        Show-Tree
        choco list --local-only --exact ant --trace
