name: .NET 06 (just Win pwsh)

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v2
#      with:
#        dotnet-version: 6.0.x
        
    - name: PowerShell lines run
      shell: pwsh
      run: |
        echo "Bla Bla"
        Install-Script -Name Show-Tree -force
